### ISSUE TITLE
Is an IP address correct in your blog? and question about externalCIDR

### ISSUE THREAD

**Issue by sykim-etri** [loxilb-io/loxilbdocs#11]
I visited [your blog](https://ko.loxilb.io/post/eks%EC%97%90%EC%84%9C-loxilb-%EB%A1%9C%EB%93%9C%EB%B0%B8%EB%9F%B0%EC%84%9C-%EC%84%A4%EC%A0%95). And I have questions about it.

1. IP Address
In your text, the IP address of LoxiLB node is '192.168.36.245'.
BUT in your topology diagram, the IP address of LoxiLB node is '192.168.3.68'.
It's confused to me.

2. externalCIDR
when configuring kube-loxilb, you set externalCIDR to '192.168.3.68/32'.
It's confused a little. Because 'EXTERNAL-IP' field is internal IP address.
If externalCIDR set to '15.164.9.61', is it working or not?
Or is it impossible to set externalCIDR to '15.164.9.61'?

Thanks for your contribution.

**Comment by backguynn** [comment]
1. 192.168.36.245 is wrong. Modified the LoxiLB node's IP to 192.168.3.68. 

2. The blog's topology diagram depicts the LoxiLB node as having two interfaces, but it actually has one interface.

The destination IP that can access EKS from the outside is the Elastic IP, but the IP entering the actual LoxiLB node is a private IP. In the configuration of the blog, all IPs heading to EKS from the outside pass through LoxiLB. Therefore, the LoxiLB node's (private) IP is used external IP in EKS.

Thanks for commenting on the error in the post. Sorry for the confusion.
